fix: fixed ConnPool incorrect handling of transaction
go-gorm/sharding pull request #42
Opened 2022-06-06 12:13 UTC by jiekun

- [X] Do only one thing
- [X] Non breaking API changes
- [X] Tested

### What did this pull request do?
Currently, sharding lib cannot start transaction correctly.

1. When entering  `(pool *ConnPool) BeginTx()` method, `pool.ConnPool` is actually `*sql.DB` and not match the `gorm.ConnPoolBeginner` interface. So `pool, nil` is returned and transaction is not started.
2. `BeginTx` / `Commit` / `Rollback` return nil when interface not match. When executing write operation, transaction is automatically called: [`BeginTransaction`](https://github.com/go-gorm/gorm/blob/v1.23.5/callbacks/transaction.go#L7). If no error returned, it will consider the transaction started by GORM and try to commit it in `CommitOrRollbackTransaction`.

In this PR, problems above are fixed by:
1. Adding correct interface assertion for `BeginTx` so the `BeginTx` could be called.
2. return `gorm. ErrInvalidTransaction` instead of nil, which could be handled in [`transaction.go`](https://github.com/go-gorm/gorm/blob/v1.23.5/callbacks/transaction.go#L12)

### User Case Description
N/A

2022-06-06 12:14 UTC, jiekun commented
@jinzhu @huacnlee PTAL

2022-06-07 02:57 UTC, jiekun commented
#43 #41 Should be fixed in this PR. We may need different struct to impl `TxCommitter`

2022-06-07 10:24 UTC, huacnlee requested changes

2022-06-07 17:14 UTC, jiekun commented on conn_pool.go
> +func (pool *ShardTxCommitter) Commit() error {
But ConnPool struct should NOT implement Commit and Rollback method. Otherwise the nested transaction wont work.

2022-07-13 11:40 UTC, jiekun commented
Hi. I'm closing this PR due to the lack of time to review and push it further. The issue is still present as described above.

2022-07-13 11:40 UTC, closed without merging